version: '2.4'

services:
  web_ui:
    container_name: web_ui
    image: wildboar-iot-gym/frontend
    ports:
      - "80:80"
  message_broker:
    container_name: rabbitmq
    image: wildboar-iot-gym/message-broker
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 15s
      timeout: 5s
      retries: 10
  database:
    container_name: mongodb
    image: wildboar-iot-gym/database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: WildBoarDB
    ports:
      - "27017:27017"
    volumes:
      - .src/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  data_generator:
    container_name: data_generator
    image: wildboar-iot-gym/data-generator
    depends_on:
      message_broker:
        condition: service_healthy
  api:
    container_name: api
    image: wildboar-iot-gym/backend
    ports:
      - "6000:80"