version: '3.7'

services:
  web_ui:
    container_name: web_ui
    image: malajski/wildboar-iot-gym:frontend
    ports:
      - "17997:80"
  data_generator:
    container_name: data_generator
    image: malajski/wildboar-iot-gym:data-generator
    restart: always
    depends_on:
      - message_broker
  #        condition: service_healthy
  api:
    container_name: api
    image: malajski/wildboar-iot-gym:backend
    restart: always
    ports:
      - "17999:80"
  message_broker:
    container_name: rabbitmq
    image: malajski/wildboar-iot-gym:message-broker
    ports:
      - "17998:5672"
      - "9090:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 15s
      timeout: 5s
      retries: 10
  database:
    container_name: mongodb
    image: malajski/wildboar-iot-gym:database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: WildBoarDB
    ports:
      - "27017:27017"
#    volumes:
#      - .src/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro