version: '3.4'

services:
  web_ui:
    container_name: web_ui
    image: ${WEB_UI_IMAGE_TAG}
    ports:
      - "80:80"
  message_broker:
    container_name: rabbitmq
    image: ${RABBITMQ_IMAGE_TAG}
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 15s
      timeout: 5s
      retries: 10
  database:
    container_name: mongodb
    image: ${MONGODB_IMAGE_TAG}
    ports:
      - "27017:27017"
  data_generator:
    container_name: data_generator
    image: ${DATA_GENERATOR_IMAGE_TAG}
    depends_on:
      message_broker:
        condition: service_healthy
  api:
    container_name: api
    image: ${API_IMAGE_TAG}
    ports:
      - "7069:80"